# Generated by Django 4.0.2 on 2024-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.IntegerField(max_length=100)),
                ('Glucose', models.IntegerField(max_length=100)),
                ('BloodPressure', models.IntegerField(max_length=100)),
                ('SkinThickness', models.IntegerField(max_length=100)),
                ('Insulin', models.IntegerField(max_length=100)),
                ('BMI', models.FloatField(max_length=100)),
                ('DiabetesPedigreeFunction', models.FloatField(max_length=100)),
                ('Age', models.IntegerField(max_length=100)),
                ('Outcome', models.BooleanField(max_length=100)),
            ],
        ),
    ]
