# Generated by Django 4.0.2 on 2024-01-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabaties',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='BMI',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='BloodPressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Glucose',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Insulin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Outcome',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Pregnancies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='SkinThickness',
            field=models.IntegerField(),
        ),
    ]
