# Generated by Django 4.0.2 on 2024-01-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_diabaties_age_alter_diabaties_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabaties',
            name='Outcome',
            field=models.IntegerField(),
        ),
    ]
