# Generated by Django 4.0.2 on 2024-01-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_excelfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabaties',
            name='Age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='BloodPressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Insulin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Outcome',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='Pregnancies',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabaties',
            name='SkinThickness',
            field=models.FloatField(),
        ),
    ]
