# Generated by Django 4.0.2 on 2024-01-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_diabaties_age_alter_diabaties_bloodpressure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diabaties',
            new_name='Diabetes',
        ),
    ]
